.TH RHADDON 1 2024-02-16 GNU
.SH NAME
rhaddon - compiler

.SH SYNOPSIS
.B rhad
[\fB\-h\fR]
[\fB\-?\fR]
[\fB\-\-help\fR]
[\fB\-v\fR]
[\fB\-\-version\fR]

.SH DESCRIPTION
.B rhaddon
programming lang

.SH OPTIONS
.TP
.BR \-h ", " \-? ", " \-\-help
hehehehehelp
.TP
.BR \-v ", " \-\-version
urrent version of Rhaddon compiler

.SH AUTHOR
author <mail@domain.smth>
